# Site
<<<<<<< HEAD
title:             Manolis Tsiliggeridis
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Physicist|Data Scientist|Analyst"
locale:             GR
baseurl: "" # the subpath of your site, e.g. /blog
url: "" https://tsilii.github.io/

=======
title:              Manolis Tsilingeridis
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Physicist|Upcoming Data Scientist|Analyst| "
locale:             Thessaloniki ,Greece
baseurl: "" #tsilii.github.io
url: "" # https://tsilii.github.io/
>>>>>>> c49357b3c5425160152ba2b93cb414b4360d9656
# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
<<<<<<< HEAD
twitter:            -
facebook:           https://www.facebook.com/manostsilii
instagram:          https://www.instagram.com/tsiliys/
github:             https://github.com/tsilii

# personal
location:           Thessaloniki, Greece
=======
twitter:            -
facebook:           https://www.facebook.com/manostsilii/
instagram:          https://www.instagram.com/tsiliys/
github:             https://www.facebook.com/manostsilii/

# personal
location:           Thessaloniki,Greece
>>>>>>> c49357b3c5425160152ba2b93cb414b4360d9656
phone:              +306988145065
email:              manolistsiliggeridis@gmail.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
